name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
env:
  OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
  OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
  HF_MODEL_REPO_DIR: model_to_sync
  # HF_REPO: stabilityai/stable-diffusion-3-medium
  HF_REPO: J5Tsai/debug-static-files
  HF_USERNAME: J5Tsai

concurrency:
  group: hf-oss-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - run: |
          git clone \
            https://huggingface.co/J5Tsai/debug-static-files \
            ${{ env.HF_MODEL_REPO_DIR }}
        env:
          GIT_LFS_SKIP_SMUDGE: 1

      - name: Test
        id: npm-ci-test
        run: npm run ci-test
        env:
          HF_TO_OSS_DEBUG_REPO_DIR: ${{ env.HF_MODEL_REPO_DIR }}

  call-workflow-to-sync:
    uses: ./.github/workflows/sync.yml
    secrets: inherit
    with:
      hf-repo: J5Tsai/debug-static-files
