name: Sync to OSS

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      OSS_ACCESS_KEY_ID:
        required: true
      OSS_ACCESS_KEY_SECRET:
        required: true
      HF_TOKEN:
        required: true

permissions:
  contents: read
env:
  OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
  OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
  HF_MODEL_REPO_DIR: model_to_sync
  # HF_REPO: stabilityai/stable-diffusion-3-medium
  HF_REPO: J5Tsai/debug-static-files
  HF_USERNAME: J5Tsai

concurrency:
  group: hf-oss-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - run: |
          git clone \
            https://huggingface.co/J5Tsai/debug-static-files \
            ${{ env.HF_MODEL_REPO_DIR }}
        env:
          GIT_LFS_SKIP_SMUDGE: 1

      - name: Test
        id: npm-ci-test
        run: npm run ci-test
        env:
          HF_TO_OSS_DEBUG_REPO_DIR: ${{ env.HF_MODEL_REPO_DIR }}

  list:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.list-action.outputs.matrix }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Checkout Repo
        run: |
          git clone \
            https://${{ env.HF_USERNAME }}:${{ secrets.HF_TOKEN }}@huggingface.co/${{ env.HF_REPO }} \
            ${{ env.HF_MODEL_REPO_DIR }}
        env:
          GIT_LFS_SKIP_SMUDGE: 1
      - name: Get HEAD
        id: get-head
        run: echo "commit=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
        working-directory: ${{ env.HF_MODEL_REPO_DIR }}
      - name: Upload to oss
        id: upload_to_oss
        uses: tvrcgo/oss-action@master
        with:
          key-id: ${{ env.OSS_ACCESS_KEY_ID }}
          key-secret: ${{ env.OSS_ACCESS_KEY_SECRET }}
          region: oss-cn-beijing
          bucket: hf-sync
          assets: |
            ${{ env.HF_MODEL_REPO_DIR }}/**:/${{ env.HF_REPO }}/${{ steps.get-head.outputs.commit }}/

      - name: List files
        id: list-action
        uses: ./actions/list
        with:
          repo-dir: ${{ env.HF_MODEL_REPO_DIR }}

  sync-oss:
    name: '#${{ matrix.task.id }} Sync ${{ matrix.task.size }} to OSS'
    runs-on: ubuntu-latest
    needs: list
    strategy:
      fail-fast: false
      max-parallel: 12
      matrix: ${{ fromJson(needs.list.outputs.matrix) }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Sync files
        id: list-action
        uses: ./actions/sync
        with:
          urls: ${{ matrix.task.urls }}
          hf-token: ${{ secrets.HF_TOKEN }}
